#############################################################################
# Makefile for building: minitwitter.app/Contents/MacOS/minitwitter
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  minitwitter.pro
# Template: app
# Command: /Users/user/anaconda2/bin/qmake -o Makefile minitwitter.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++11 -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../anaconda2/include/qt -I../../../anaconda2/include/qt/QtGui -I../../../anaconda2/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../anaconda2/mkspecs/macx-clang
QMAKE         = /Users/user/anaconda2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = minitwitter1.0.0
DISTDIR = /Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project/.tmp/minitwitter1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/user/anaconda2/lib
LIBS          = $(SUBLIBS) -L/Users/user/anaconda2/lib -lQt5Gui -framework DiskArbitration -framework IOKit -lQt5Core -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/objects/datetime.cpp \
		src/main/main.cpp \
		src/Qt/searchwin.cpp \
		src/Qt/toolsbar.cpp \
		src/objects/tweet.cpp \
		src/objects/twiteng.cpp \
		src/Qt/twitgui.cpp \
		src/objects/user.cpp moc_searchwin.cpp \
		moc_toolsbar.cpp \
		moc_twitgui.cpp
OBJECTS       = datetime.o \
		main.o \
		searchwin.o \
		toolsbar.o \
		tweet.o \
		twiteng.o \
		twitgui.o \
		user.o \
		moc_searchwin.o \
		moc_toolsbar.o \
		moc_twitgui.o
DIST          = ../../../anaconda2/mkspecs/features/spec_pre.prf \
		../../../anaconda2/mkspecs/qdevice.pri \
		../../../anaconda2/mkspecs/features/device_config.prf \
		../../../anaconda2/mkspecs/common/unix.conf \
		../../../anaconda2/mkspecs/common/mac.conf \
		../../../anaconda2/mkspecs/common/macx.conf \
		../../../anaconda2/mkspecs/common/sanitize.conf \
		../../../anaconda2/mkspecs/common/gcc-base.conf \
		../../../anaconda2/mkspecs/common/gcc-base-mac.conf \
		../../../anaconda2/mkspecs/common/clang.conf \
		../../../anaconda2/mkspecs/common/clang-mac.conf \
		../../../anaconda2/mkspecs/qconfig.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda2/mkspecs/features/qt_functions.prf \
		../../../anaconda2/mkspecs/features/qt_config.prf \
		../../../anaconda2/mkspecs/macx-clang/qmake.conf \
		../../../anaconda2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../../anaconda2/mkspecs/features/default_pre.prf \
		../../../anaconda2/mkspecs/features/mac/default_pre.prf \
		../../../anaconda2/mkspecs/features/resolve_config.prf \
		../../../anaconda2/mkspecs/features/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/sdk.prf \
		../../../anaconda2/mkspecs/features/mac/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/objective_c.prf \
		../../../anaconda2/mkspecs/features/warn_on.prf \
		../../../anaconda2/mkspecs/features/qt.prf \
		../../../anaconda2/mkspecs/features/resources.prf \
		../../../anaconda2/mkspecs/features/moc.prf \
		../../../anaconda2/mkspecs/features/unix/opengl.prf \
		../../../anaconda2/mkspecs/features/unix/thread.prf \
		../../../anaconda2/mkspecs/features/file_copies.prf \
		../../../anaconda2/mkspecs/features/mac/rez.prf \
		../../../anaconda2/mkspecs/features/testcase_targets.prf \
		../../../anaconda2/mkspecs/features/exceptions.prf \
		../../../anaconda2/mkspecs/features/yacc.prf \
		../../../anaconda2/mkspecs/features/lex.prf \
		minitwitter.pro src/objects/datetime.h \
		src/utils/heap.h \
		src/utils/msort.h \
		src/Qt/searchwin.h \
		src/objects/tagdata.h \
		src/Qt/toolsbar.h \
		src/objects/tweet.h \
		src/objects/twiteng.h \
		src/Qt/twitgui.h \
		src/objects/user.h src/objects/datetime.cpp \
		src/main/main.cpp \
		src/Qt/searchwin.cpp \
		src/Qt/toolsbar.cpp \
		src/objects/tweet.cpp \
		src/objects/twiteng.cpp \
		src/Qt/twitgui.cpp \
		src/objects/user.cpp
QMAKE_TARGET  = minitwitter
DESTDIR       = 
TARGET        = minitwitter.app/Contents/MacOS/minitwitter


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d minitwitter.app/Contents/MacOS/ || mkdir -p minitwitter.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: minitwitter.pro ../../../anaconda2/mkspecs/macx-clang/qmake.conf ../../../anaconda2/mkspecs/features/spec_pre.prf \
		../../../anaconda2/mkspecs/qdevice.pri \
		../../../anaconda2/mkspecs/features/device_config.prf \
		../../../anaconda2/mkspecs/common/unix.conf \
		../../../anaconda2/mkspecs/common/mac.conf \
		../../../anaconda2/mkspecs/common/macx.conf \
		../../../anaconda2/mkspecs/common/sanitize.conf \
		../../../anaconda2/mkspecs/common/gcc-base.conf \
		../../../anaconda2/mkspecs/common/gcc-base-mac.conf \
		../../../anaconda2/mkspecs/common/clang.conf \
		../../../anaconda2/mkspecs/common/clang-mac.conf \
		../../../anaconda2/mkspecs/qconfig.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda2/mkspecs/features/qt_functions.prf \
		../../../anaconda2/mkspecs/features/qt_config.prf \
		../../../anaconda2/mkspecs/macx-clang/qmake.conf \
		../../../anaconda2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../../anaconda2/mkspecs/features/default_pre.prf \
		../../../anaconda2/mkspecs/features/mac/default_pre.prf \
		../../../anaconda2/mkspecs/features/resolve_config.prf \
		../../../anaconda2/mkspecs/features/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/sdk.prf \
		../../../anaconda2/mkspecs/features/mac/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/objective_c.prf \
		../../../anaconda2/mkspecs/features/warn_on.prf \
		../../../anaconda2/mkspecs/features/qt.prf \
		../../../anaconda2/mkspecs/features/resources.prf \
		../../../anaconda2/mkspecs/features/moc.prf \
		../../../anaconda2/mkspecs/features/unix/opengl.prf \
		../../../anaconda2/mkspecs/features/unix/thread.prf \
		../../../anaconda2/mkspecs/features/file_copies.prf \
		../../../anaconda2/mkspecs/features/mac/rez.prf \
		../../../anaconda2/mkspecs/features/testcase_targets.prf \
		../../../anaconda2/mkspecs/features/exceptions.prf \
		../../../anaconda2/mkspecs/features/yacc.prf \
		../../../anaconda2/mkspecs/features/lex.prf \
		minitwitter.pro \
		../../../anaconda2/lib/libQt5Gui.prl \
		../../../anaconda2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile minitwitter.pro
../../../anaconda2/mkspecs/features/spec_pre.prf:
../../../anaconda2/mkspecs/qdevice.pri:
../../../anaconda2/mkspecs/features/device_config.prf:
../../../anaconda2/mkspecs/common/unix.conf:
../../../anaconda2/mkspecs/common/mac.conf:
../../../anaconda2/mkspecs/common/macx.conf:
../../../anaconda2/mkspecs/common/sanitize.conf:
../../../anaconda2/mkspecs/common/gcc-base.conf:
../../../anaconda2/mkspecs/common/gcc-base-mac.conf:
../../../anaconda2/mkspecs/common/clang.conf:
../../../anaconda2/mkspecs/common/clang-mac.conf:
../../../anaconda2/mkspecs/qconfig.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_clucene_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_core.pri:
../../../anaconda2/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda2/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_help.pri:
../../../anaconda2/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_macextras.pri:
../../../anaconda2/mkspecs/modules/qt_lib_macextras_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_network.pri:
../../../anaconda2/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda2/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda2/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_script.pri:
../../../anaconda2/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda2/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda2/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda2/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda2/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda2/mkspecs/features/qt_functions.prf:
../../../anaconda2/mkspecs/features/qt_config.prf:
../../../anaconda2/mkspecs/macx-clang/qmake.conf:
../../../anaconda2/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../anaconda2/mkspecs/features/exclusive_builds.prf:
../../../anaconda2/mkspecs/features/default_pre.prf:
../../../anaconda2/mkspecs/features/mac/default_pre.prf:
../../../anaconda2/mkspecs/features/resolve_config.prf:
../../../anaconda2/mkspecs/features/default_post.prf:
../../../anaconda2/mkspecs/features/mac/sdk.prf:
../../../anaconda2/mkspecs/features/mac/default_post.prf:
../../../anaconda2/mkspecs/features/mac/objective_c.prf:
../../../anaconda2/mkspecs/features/warn_on.prf:
../../../anaconda2/mkspecs/features/qt.prf:
../../../anaconda2/mkspecs/features/resources.prf:
../../../anaconda2/mkspecs/features/moc.prf:
../../../anaconda2/mkspecs/features/unix/opengl.prf:
../../../anaconda2/mkspecs/features/unix/thread.prf:
../../../anaconda2/mkspecs/features/file_copies.prf:
../../../anaconda2/mkspecs/features/mac/rez.prf:
../../../anaconda2/mkspecs/features/testcase_targets.prf:
../../../anaconda2/mkspecs/features/exceptions.prf:
../../../anaconda2/mkspecs/features/yacc.prf:
../../../anaconda2/mkspecs/features/lex.prf:
minitwitter.pro:
../../../anaconda2/lib/libQt5Gui.prl:
../../../anaconda2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile minitwitter.pro

qmake_all: FORCE

minitwitter.app/Contents/PkgInfo: 
	@test -d minitwitter.app/Contents || mkdir -p minitwitter.app/Contents
	@$(DEL_FILE) minitwitter.app/Contents/PkgInfo
	@echo "APPL????" > minitwitter.app/Contents/PkgInfo
minitwitter.app/Contents/Resources/empty.lproj: 
	@test -d minitwitter.app/Contents/Resources || mkdir -p minitwitter.app/Contents/Resources
	@touch minitwitter.app/Contents/Resources/empty.lproj
	
minitwitter.app/Contents/Info.plist: 
	@test -d minitwitter.app/Contents || mkdir -p minitwitter.app/Contents
	@$(DEL_FILE) minitwitter.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,USC.minitwitter,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,minitwitter,g" -e "s,@LIBRARY@,minitwitter,g" -e "s,@TYPEINFO@,????,g" ../../../anaconda2/mkspecs/macx-clang/Info.plist.app >minitwitter.app/Contents/Info.plist

all: Makefile \
		minitwitter.app/Contents/PkgInfo \
		minitwitter.app/Contents/Resources/empty.lproj \
		minitwitter.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/objects/datetime.h src/utils/heap.h src/utils/msort.h src/Qt/searchwin.h src/objects/tagdata.h src/Qt/toolsbar.h src/objects/tweet.h src/objects/twiteng.h src/Qt/twitgui.h src/objects/user.h $(DISTDIR)/
	$(COPY_FILE) --parents src/objects/datetime.cpp src/main/main.cpp src/Qt/searchwin.cpp src/Qt/toolsbar.cpp src/objects/tweet.cpp src/objects/twiteng.cpp src/Qt/twitgui.cpp src/objects/user.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r minitwitter.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_searchwin.cpp moc_toolsbar.cpp moc_twitgui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_searchwin.cpp moc_toolsbar.cpp moc_twitgui.cpp
moc_searchwin.cpp: ../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda2/include/qt/QtGui/QPalette \
		../../../anaconda2/include/qt/QtGui/qpalette.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda2/include/qt/QtGui/qcolor.h \
		../../../anaconda2/include/qt/QtGui/qrgb.h \
		../../../anaconda2/include/qt/QtCore/qstringlist.h \
		../../../anaconda2/include/qt/QtCore/qlist.h \
		../../../anaconda2/include/qt/QtCore/qalgorithms.h \
		../../../anaconda2/include/qt/QtCore/qiterator.h \
		../../../anaconda2/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda2/include/qt/QtCore/qpair.h \
		../../../anaconda2/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda2/include/qt/QtCore/qregexp.h \
		../../../anaconda2/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda2/include/qt/QtGui/qrgba64.h \
		../../../anaconda2/include/qt/QtGui/qbrush.h \
		../../../anaconda2/include/qt/QtCore/qpoint.h \
		../../../anaconda2/include/qt/QtCore/qvector.h \
		../../../anaconda2/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda2/include/qt/QtGui/qmatrix.h \
		../../../anaconda2/include/qt/QtGui/qpolygon.h \
		../../../anaconda2/include/qt/QtCore/qrect.h \
		../../../anaconda2/include/qt/QtCore/qmargins.h \
		../../../anaconda2/include/qt/QtCore/qsize.h \
		../../../anaconda2/include/qt/QtGui/qregion.h \
		../../../anaconda2/include/qt/QtCore/qdatastream.h \
		../../../anaconda2/include/qt/QtCore/qiodevice.h \
		../../../anaconda2/include/qt/QtCore/qobject.h \
		../../../anaconda2/include/qt/QtCore/qcoreevent.h \
		../../../anaconda2/include/qt/QtCore/qmetatype.h \
		../../../anaconda2/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda2/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda2/include/qt/QtCore/qobject_impl.h \
		../../../anaconda2/include/qt/QtCore/qline.h \
		../../../anaconda2/include/qt/QtGui/qtransform.h \
		../../../anaconda2/include/qt/QtGui/qpainterpath.h \
		../../../anaconda2/include/qt/QtGui/qimage.h \
		../../../anaconda2/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda2/include/qt/QtGui/qpixelformat.h \
		../../../anaconda2/include/qt/QtGui/qpixmap.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda2/include/qt/QtCore/qshareddata.h \
		../../../anaconda2/include/qt/QtCore/qhash.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer_impl.h \
		src/Qt/searchwin.h
	/Users/user/anaconda2/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/user/anaconda2/mkspecs/macx-clang -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/anaconda2/include/qt -I/Users/user/anaconda2/include/qt/QtGui -I/Users/user/anaconda2/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include src/Qt/searchwin.h -o moc_searchwin.cpp

moc_toolsbar.cpp: ../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		src/Qt/toolsbar.h
	/Users/user/anaconda2/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/user/anaconda2/mkspecs/macx-clang -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/anaconda2/include/qt -I/Users/user/anaconda2/include/qt/QtGui -I/Users/user/anaconda2/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include src/Qt/toolsbar.h -o moc_toolsbar.cpp

moc_twitgui.cpp: src/Qt/searchwin.h \
		../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda2/include/qt/QtGui/QPalette \
		../../../anaconda2/include/qt/QtGui/qpalette.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda2/include/qt/QtGui/qcolor.h \
		../../../anaconda2/include/qt/QtGui/qrgb.h \
		../../../anaconda2/include/qt/QtCore/qstringlist.h \
		../../../anaconda2/include/qt/QtCore/qlist.h \
		../../../anaconda2/include/qt/QtCore/qalgorithms.h \
		../../../anaconda2/include/qt/QtCore/qiterator.h \
		../../../anaconda2/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda2/include/qt/QtCore/qpair.h \
		../../../anaconda2/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda2/include/qt/QtCore/qregexp.h \
		../../../anaconda2/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda2/include/qt/QtGui/qrgba64.h \
		../../../anaconda2/include/qt/QtGui/qbrush.h \
		../../../anaconda2/include/qt/QtCore/qpoint.h \
		../../../anaconda2/include/qt/QtCore/qvector.h \
		../../../anaconda2/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda2/include/qt/QtGui/qmatrix.h \
		../../../anaconda2/include/qt/QtGui/qpolygon.h \
		../../../anaconda2/include/qt/QtCore/qrect.h \
		../../../anaconda2/include/qt/QtCore/qmargins.h \
		../../../anaconda2/include/qt/QtCore/qsize.h \
		../../../anaconda2/include/qt/QtGui/qregion.h \
		../../../anaconda2/include/qt/QtCore/qdatastream.h \
		../../../anaconda2/include/qt/QtCore/qiodevice.h \
		../../../anaconda2/include/qt/QtCore/qobject.h \
		../../../anaconda2/include/qt/QtCore/qcoreevent.h \
		../../../anaconda2/include/qt/QtCore/qmetatype.h \
		../../../anaconda2/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda2/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda2/include/qt/QtCore/qobject_impl.h \
		../../../anaconda2/include/qt/QtCore/qline.h \
		../../../anaconda2/include/qt/QtGui/qtransform.h \
		../../../anaconda2/include/qt/QtGui/qpainterpath.h \
		../../../anaconda2/include/qt/QtGui/qimage.h \
		../../../anaconda2/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda2/include/qt/QtGui/qpixelformat.h \
		../../../anaconda2/include/qt/QtGui/qpixmap.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda2/include/qt/QtCore/qshareddata.h \
		../../../anaconda2/include/qt/QtCore/qhash.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer_impl.h \
		src/Qt/toolsbar.h \
		src/Qt/twitgui.h
	/Users/user/anaconda2/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/user/anaconda2/mkspecs/macx-clang -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/Documents/MiniTwitter/MiniTwitter-From-CSCI104-Project -I/Users/user/anaconda2/include/qt -I/Users/user/anaconda2/include/qt/QtGui -I/Users/user/anaconda2/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include src/Qt/twitgui.h -o moc_twitgui.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

datetime.o: src/objects/datetime.cpp src/objects/datetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datetime.o src/objects/datetime.cpp

main.o: src/main/main.cpp src/Qt/twitgui.h \
		src/Qt/searchwin.h \
		../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda2/include/qt/QtGui/QPalette \
		../../../anaconda2/include/qt/QtGui/qpalette.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda2/include/qt/QtGui/qcolor.h \
		../../../anaconda2/include/qt/QtGui/qrgb.h \
		../../../anaconda2/include/qt/QtCore/qstringlist.h \
		../../../anaconda2/include/qt/QtCore/qlist.h \
		../../../anaconda2/include/qt/QtCore/qalgorithms.h \
		../../../anaconda2/include/qt/QtCore/qiterator.h \
		../../../anaconda2/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda2/include/qt/QtCore/qpair.h \
		../../../anaconda2/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda2/include/qt/QtCore/qregexp.h \
		../../../anaconda2/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda2/include/qt/QtGui/qrgba64.h \
		../../../anaconda2/include/qt/QtGui/qbrush.h \
		../../../anaconda2/include/qt/QtCore/qpoint.h \
		../../../anaconda2/include/qt/QtCore/qvector.h \
		../../../anaconda2/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda2/include/qt/QtGui/qmatrix.h \
		../../../anaconda2/include/qt/QtGui/qpolygon.h \
		../../../anaconda2/include/qt/QtCore/qrect.h \
		../../../anaconda2/include/qt/QtCore/qmargins.h \
		../../../anaconda2/include/qt/QtCore/qsize.h \
		../../../anaconda2/include/qt/QtGui/qregion.h \
		../../../anaconda2/include/qt/QtCore/qdatastream.h \
		../../../anaconda2/include/qt/QtCore/qiodevice.h \
		../../../anaconda2/include/qt/QtCore/qobject.h \
		../../../anaconda2/include/qt/QtCore/qcoreevent.h \
		../../../anaconda2/include/qt/QtCore/qmetatype.h \
		../../../anaconda2/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda2/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda2/include/qt/QtCore/qobject_impl.h \
		../../../anaconda2/include/qt/QtCore/qline.h \
		../../../anaconda2/include/qt/QtGui/qtransform.h \
		../../../anaconda2/include/qt/QtGui/qpainterpath.h \
		../../../anaconda2/include/qt/QtGui/qimage.h \
		../../../anaconda2/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda2/include/qt/QtGui/qpixelformat.h \
		../../../anaconda2/include/qt/QtGui/qpixmap.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda2/include/qt/QtCore/qshareddata.h \
		../../../anaconda2/include/qt/QtCore/qhash.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer_impl.h \
		src/Qt/toolsbar.h \
		../../../anaconda2/include/qt/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main/main.cpp

searchwin.o: src/Qt/searchwin.cpp src/Qt/searchwin.h \
		../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda2/include/qt/QtGui/QPalette \
		../../../anaconda2/include/qt/QtGui/qpalette.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda2/include/qt/QtGui/qcolor.h \
		../../../anaconda2/include/qt/QtGui/qrgb.h \
		../../../anaconda2/include/qt/QtCore/qstringlist.h \
		../../../anaconda2/include/qt/QtCore/qlist.h \
		../../../anaconda2/include/qt/QtCore/qalgorithms.h \
		../../../anaconda2/include/qt/QtCore/qiterator.h \
		../../../anaconda2/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda2/include/qt/QtCore/qpair.h \
		../../../anaconda2/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda2/include/qt/QtCore/qregexp.h \
		../../../anaconda2/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda2/include/qt/QtGui/qrgba64.h \
		../../../anaconda2/include/qt/QtGui/qbrush.h \
		../../../anaconda2/include/qt/QtCore/qpoint.h \
		../../../anaconda2/include/qt/QtCore/qvector.h \
		../../../anaconda2/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda2/include/qt/QtGui/qmatrix.h \
		../../../anaconda2/include/qt/QtGui/qpolygon.h \
		../../../anaconda2/include/qt/QtCore/qrect.h \
		../../../anaconda2/include/qt/QtCore/qmargins.h \
		../../../anaconda2/include/qt/QtCore/qsize.h \
		../../../anaconda2/include/qt/QtGui/qregion.h \
		../../../anaconda2/include/qt/QtCore/qdatastream.h \
		../../../anaconda2/include/qt/QtCore/qiodevice.h \
		../../../anaconda2/include/qt/QtCore/qobject.h \
		../../../anaconda2/include/qt/QtCore/qcoreevent.h \
		../../../anaconda2/include/qt/QtCore/qmetatype.h \
		../../../anaconda2/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda2/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda2/include/qt/QtCore/qobject_impl.h \
		../../../anaconda2/include/qt/QtCore/qline.h \
		../../../anaconda2/include/qt/QtGui/qtransform.h \
		../../../anaconda2/include/qt/QtGui/qpainterpath.h \
		../../../anaconda2/include/qt/QtGui/qimage.h \
		../../../anaconda2/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda2/include/qt/QtGui/qpixelformat.h \
		../../../anaconda2/include/qt/QtGui/qpixmap.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda2/include/qt/QtCore/qshareddata.h \
		../../../anaconda2/include/qt/QtCore/qhash.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchwin.o src/Qt/searchwin.cpp

toolsbar.o: src/Qt/toolsbar.cpp src/Qt/toolsbar.h \
		../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolsbar.o src/Qt/toolsbar.cpp

tweet.o: src/objects/tweet.cpp src/objects/tweet.h \
		src/objects/datetime.h \
		src/objects/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tweet.o src/objects/tweet.cpp

twiteng.o: src/objects/twiteng.cpp src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twiteng.o src/objects/twiteng.cpp

twitgui.o: src/Qt/twitgui.cpp src/Qt/twitgui.h \
		src/Qt/searchwin.h \
		../../../anaconda2/include/qt/QtCore/QString \
		../../../anaconda2/include/qt/QtCore/qstring.h \
		../../../anaconda2/include/qt/QtCore/qchar.h \
		../../../anaconda2/include/qt/QtCore/qglobal.h \
		../../../anaconda2/include/qt/QtCore/qconfig.h \
		../../../anaconda2/include/qt/QtCore/qfeatures.h \
		../../../anaconda2/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda2/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda2/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda2/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda2/include/qt/QtCore/qtypetraits.h \
		../../../anaconda2/include/qt/QtCore/qisenum.h \
		../../../anaconda2/include/qt/QtCore/qsysinfo.h \
		../../../anaconda2/include/qt/QtCore/qlogging.h \
		../../../anaconda2/include/qt/QtCore/qflags.h \
		../../../anaconda2/include/qt/QtCore/qatomic.h \
		../../../anaconda2/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda2/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda2/include/qt/QtCore/qatomic_gcc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv7.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv6.h \
		../../../anaconda2/include/qt/QtCore/qatomic_armv5.h \
		../../../anaconda2/include/qt/QtCore/qatomic_ia64.h \
		../../../anaconda2/include/qt/QtCore/qatomic_x86.h \
		../../../anaconda2/include/qt/QtCore/qatomic_unix.h \
		../../../anaconda2/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda2/include/qt/QtCore/qmutex.h \
		../../../anaconda2/include/qt/QtCore/qnumeric.h \
		../../../anaconda2/include/qt/QtCore/qversiontagging.h \
		../../../anaconda2/include/qt/QtCore/qbytearray.h \
		../../../anaconda2/include/qt/QtCore/qrefcount.h \
		../../../anaconda2/include/qt/QtCore/qnamespace.h \
		../../../anaconda2/include/qt/QtCore/qarraydata.h \
		../../../anaconda2/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda2/include/qt/QtGui/QPalette \
		../../../anaconda2/include/qt/QtGui/qpalette.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda2/include/qt/QtGui/qcolor.h \
		../../../anaconda2/include/qt/QtGui/qrgb.h \
		../../../anaconda2/include/qt/QtCore/qstringlist.h \
		../../../anaconda2/include/qt/QtCore/qlist.h \
		../../../anaconda2/include/qt/QtCore/qalgorithms.h \
		../../../anaconda2/include/qt/QtCore/qiterator.h \
		../../../anaconda2/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda2/include/qt/QtCore/qpair.h \
		../../../anaconda2/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda2/include/qt/QtCore/qregexp.h \
		../../../anaconda2/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda2/include/qt/QtGui/qrgba64.h \
		../../../anaconda2/include/qt/QtGui/qbrush.h \
		../../../anaconda2/include/qt/QtCore/qpoint.h \
		../../../anaconda2/include/qt/QtCore/qvector.h \
		../../../anaconda2/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda2/include/qt/QtGui/qmatrix.h \
		../../../anaconda2/include/qt/QtGui/qpolygon.h \
		../../../anaconda2/include/qt/QtCore/qrect.h \
		../../../anaconda2/include/qt/QtCore/qmargins.h \
		../../../anaconda2/include/qt/QtCore/qsize.h \
		../../../anaconda2/include/qt/QtGui/qregion.h \
		../../../anaconda2/include/qt/QtCore/qdatastream.h \
		../../../anaconda2/include/qt/QtCore/qiodevice.h \
		../../../anaconda2/include/qt/QtCore/qobject.h \
		../../../anaconda2/include/qt/QtCore/qcoreevent.h \
		../../../anaconda2/include/qt/QtCore/qmetatype.h \
		../../../anaconda2/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda2/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda2/include/qt/QtCore/qobject_impl.h \
		../../../anaconda2/include/qt/QtCore/qline.h \
		../../../anaconda2/include/qt/QtGui/qtransform.h \
		../../../anaconda2/include/qt/QtGui/qpainterpath.h \
		../../../anaconda2/include/qt/QtGui/qimage.h \
		../../../anaconda2/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda2/include/qt/QtGui/qpixelformat.h \
		../../../anaconda2/include/qt/QtGui/qpixmap.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda2/include/qt/QtCore/qshareddata.h \
		../../../anaconda2/include/qt/QtCore/qhash.h \
		../../../anaconda2/include/qt/QtCore/qsharedpointer_impl.h \
		src/Qt/toolsbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twitgui.o src/Qt/twitgui.cpp

user.o: src/objects/user.cpp src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o src/objects/user.cpp

moc_searchwin.o: moc_searchwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchwin.o moc_searchwin.cpp

moc_toolsbar.o: moc_toolsbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolsbar.o moc_toolsbar.cpp

moc_twitgui.o: moc_twitgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twitgui.o moc_twitgui.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

