#############################################################################
# Makefile for building: minitwitter
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Apr 4 15:04:44 2018
# Project:  minitwitter.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile minitwitter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/objects/datetime.cpp \
		src/main/main.cpp \
		src/Qt/searchwin.cpp \
		src/Qt/toolsbar.cpp \
		src/objects/tweet.cpp \
		src/objects/twiteng.cpp \
		src/Qt/twitgui.cpp \
		src/objects/user.cpp moc_searchwin.cpp \
		moc_toolsbar.cpp \
		moc_twitgui.cpp
OBJECTS       = datetime.o \
		main.o \
		searchwin.o \
		toolsbar.o \
		tweet.o \
		twiteng.o \
		twitgui.o \
		user.o \
		moc_searchwin.o \
		moc_toolsbar.o \
		moc_twitgui.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		minitwitter.pro
QMAKE_TARGET  = minitwitter
DESTDIR       = 
TARGET        = minitwitter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: minitwitter.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile minitwitter.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile minitwitter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/minitwitter1.0.0 || $(MKDIR) .tmp/minitwitter1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/minitwitter1.0.0/ && $(COPY_FILE) --parents src/objects/datetime.h src/utils/heap.h src/utils/msort.h src/Qt/searchwin.h src/objects/tagdata.h src/Qt/toolsbar.h src/objects/tweet.h src/objects/twiteng.h src/Qt/twitgui.h src/objects/user.h .tmp/minitwitter1.0.0/ && $(COPY_FILE) --parents src/objects/datetime.cpp src/main/main.cpp src/Qt/searchwin.cpp src/Qt/toolsbar.cpp src/objects/tweet.cpp src/objects/twiteng.cpp src/Qt/twitgui.cpp src/objects/user.cpp .tmp/minitwitter1.0.0/ && (cd `dirname .tmp/minitwitter1.0.0` && $(TAR) minitwitter1.0.0.tar minitwitter1.0.0 && $(COMPRESS) minitwitter1.0.0.tar) && $(MOVE) `dirname .tmp/minitwitter1.0.0`/minitwitter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/minitwitter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_searchwin.cpp moc_toolsbar.cpp moc_twitgui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_searchwin.cpp moc_toolsbar.cpp moc_twitgui.cpp
moc_searchwin.cpp: src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h \
		src/Qt/searchwin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/Qt/searchwin.h -o moc_searchwin.cpp

moc_toolsbar.cpp: src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h \
		src/Qt/toolsbar.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/Qt/toolsbar.h -o moc_toolsbar.cpp

moc_twitgui.cpp: src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h \
		src/Qt/searchwin.h \
		src/Qt/toolsbar.h \
		src/Qt/twitgui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/Qt/twitgui.h -o moc_twitgui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

datetime.o: src/objects/datetime.cpp src/objects/datetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datetime.o src/objects/datetime.cpp

main.o: src/main/main.cpp src/Qt/twitgui.h \
		src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h \
		src/Qt/searchwin.h \
		src/Qt/toolsbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main/main.cpp

searchwin.o: src/Qt/searchwin.cpp src/Qt/searchwin.h \
		src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchwin.o src/Qt/searchwin.cpp

toolsbar.o: src/Qt/toolsbar.cpp src/Qt/toolsbar.h \
		src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolsbar.o src/Qt/toolsbar.cpp

tweet.o: src/objects/tweet.cpp src/objects/tweet.h \
		src/objects/datetime.h \
		src/objects/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tweet.o src/objects/tweet.cpp

twiteng.o: src/objects/twiteng.cpp src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twiteng.o src/objects/twiteng.cpp

twitgui.o: src/Qt/twitgui.cpp src/Qt/twitgui.h \
		src/objects/twiteng.h \
		src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h \
		src/utils/heap.h \
		src/objects/tagdata.h \
		src/Qt/searchwin.h \
		src/Qt/toolsbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twitgui.o src/Qt/twitgui.cpp

user.o: src/objects/user.cpp src/objects/user.h \
		src/objects/tweet.h \
		src/objects/datetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o src/objects/user.cpp

moc_searchwin.o: moc_searchwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchwin.o moc_searchwin.cpp

moc_toolsbar.o: moc_toolsbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolsbar.o moc_toolsbar.cpp

moc_twitgui.o: moc_twitgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twitgui.o moc_twitgui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

